return {
  -- ({
  --  'rose-pine/neovim',
  --  name = 'rose-pine',
  --  config = function() 
  --   vim.cmd('colorscheme rose-pine')
  --  end
  -- }),
  --
  -- ('nvim-treesitter/nvim-treesitter', {run = ':TSUpdate'}),
  -- ("nvim-treesitter/playground"),
  --
  -- ('theprimeagen/harpoon'),
  -- ('mbbill/undotree'),
  -- ('tpope/vim-fugitive'),
  --
  -- {
  --  'VonHeikemen/lsp-zero.nvim',
  --  requires = {
  --   -- LSP Support
  --   {'neovim/nvim-lspconfig'},
  --   {'williamboman/mason.nvim'},
  --   {'williamboman/mason-lspconfig.nvim'},
  --
  --   -- Autocompletion
  --   {"hrsh7th/cmp-nvim-lsp"},
  --   {"hrsh7th/cmp-nvim-lua"},
  --   {"hrsh7th/cmp-buffer"},
  --   {"hrsh7th/cmp-path"},
  --   {"hrsh7th/cmp-cmdline"},
  --   {"hrsh7th/nvim-cmp"},
  --   {"saadparwaiz1/cmp_luasnip"},
  --   {"j-hui/fidget.nvim"},
  --   {"L3MON4D3/LuaSnip"},
  --  }
  -- },
}
